### PR TITLE
Update Section 5 with number of devices required

### PR DESCRIPTION
**Pull request by myarmolinsky**
Update Section 5 with number of devices required

Change-type: patch
Signed-off-by: Matthew Yarmolinsky <matthew-timothy@balena.io>

### CODE REVIEW

**Comment by myarmolinsky** [comment]
@balena-ci I self certify!

**Comment by vipulgupta2048** [comment]
@balena-ci I self-certify!

**Comment by vipulgupta2048** [comment]
@balena-ci I self certify!

**Review by stathismor — APPROVED** [review]

**Review by stathismor — APPROVED** [review]

**Comment by stathismor** [comment]
@balena-ci retest

**Pull request merged**
